### ISSUE TITLE
GeoJSONVectorTileLayer和VectorTileLayer identify出来的结果，数据结构不同

### ISSUE THREAD

**Issue by deyihu** [maptalks/issues#101]
![FG8O2EPSU`$ (LYPPOLAA8F](https://user-images.githubusercontent.com/25998927/182085192-bb831b18-2759-45ff-add9-be6e21f65f59.png)

![(TND5MQ`7Z@V5HM2S$2`5@N](https://user-images.githubusercontent.com/25998927/182085135-8a2dbfc9-17ff-4c06-9140-3b76d88cbf27.png)

GeoJSONVectorTileLayer 返回的数据符合geojson规范，但是VectorTileLayer 返回的数据结果不符合geojson规范，希望vt的数据结构像geojsonvt一样进行统一掉

**Comment by fuzhenn** [comment]
已经在VectorTileLayer中把vt结果转换为了geojson风格。
