### ISSUE TITLE
把GroupGLLayer的bloom打开后，threeLayer里面渲染的对象没有显示出来，但是可以检测到鼠标事件

### ISSUE THREAD

**Issue by tttttttanghc** [maptalks/issues#102]
把GroupGLLayer的bloom打开后，threeLayer里面渲染的对象没有显示出来，但是可以检测到鼠标事件.
示例代码：https://codepen.io/tttttttanghc/pen/bGvrZrz?editors=1010

**Comment by deyihu** [comment]
fix by https://github.com/maptalks/maptalks.three/commit/04df878d8a43c4aa38a112505de30849e9855821
