### ISSUE TITLE
最新版本vt中 pointlayer icon图标如果缩放模糊

### ISSUE THREAD

**Issue by deyihu** [maptalks/issues#106]
https://codepen.io/deyihu/pen/YzajXBY?editors=1010

除非设置symbol的大小和图片本身大小一样，才不模糊，上一个版本不是这样的，

**Comment by tttttttanghc** [comment]
我试了下，宽高与原图一样的情况下，在关闭antialias.enable或者设置renderToPointRenderTarget:true的情况下才比较清楚，不然还是很糊

**Comment by fuzhenn** [comment]
fixed in vt@0.74.4
