### ISSUE TITLE
PointLayer同时存在两组marker时，移除任一组会报错，然后整个地图就不能动了

### ISSUE THREAD

**Issue by tttttttanghc** [maptalks/issues#113]
![9(P`UYDJYVPH`7S$P$C (YQ](https://user-images.githubusercontent.com/75002405/184129294-37b0b311-6744-438b-ab47-c2729bc6388b.jpg)
PointLayer同时存在两组marker时，移除任一组会报错，然后整个地图就不能动了
复现代码：https://codepen.io/tttttttanghc/pen/PoRBYZO，点左上角的按钮就会触发报错了

**Comment by tttttttanghc** [comment]
复现代码：https://codepen.io/tttttttanghc/pen/PoRBYZO

**Comment by fuzhenn** [comment]
fixed in vt@0.74.3
