### ISSUE TITLE
挖方分析需要实现保留挖方内的图形

### ISSUE THREAD

**Issue by fuzhenn** [maptalks/issues#117]
例如挖方中的管线：

![X~`B A1USI (E~6~U)_YAA6](https://user-images.githubusercontent.com/13678919/186049671-5826faf2-8a5c-4d45-b65d-9de31015f629.jpg)

**Comment by liubgithub** [comment]
分析里面已增加了对excludeLayers的支持，可以排除对指定图层进行分析，例如：
``` new maptalks.ExcavateAnalysis({ excludeLayers: ['layerId'] });```
