### ISSUE TITLE
vt>=v0.69.0后，PolygonLayer对于polygonOpacity渲染结果与VectorLayer有较大差异

### ISSUE THREAD

**Issue by cXiaof** [maptalks/issues#118]
同样symbol的情况下（基于[[面的基本样式](http://examples.maptalks.com/vectorLayer/polygonLayer/polygonSymbol)]例子仅改动透明度）
```js
//symbol
{
  polygonFill: "rgb(135,196,240)",
  polygonOpacity: 0.5,
  lineColor: "#1bbc9b",
  lineWidth: 6,
  lineJoin: "round",
  lineCap: "round",
  lineDasharray: null,
  lineOpacity: 1,
}
```
VectorLayer的渲染结果
![v](https://user-images.githubusercontent.com/20589819/186060803-0ae8cbb6-2d09-4ff0-9e42-2a11227d2257.png)
vt<=v0.68.0时，PolygonLayer的渲染结果，虽然与VectorLayer稍有差异但还是大致相同（maptalks-gl-layers<=v0.4.1）
![vt68](https://user-images.githubusercontent.com/20589819/186060908-a63920a8-de9d-4e91-98da-767d6bc0f05d.png)
但是当vt>=v0.69.0后，对于polygonOpacity渲染方式有明显不同（maptalks-gl-layers>=v0.5.0）
![vt69](https://user-images.githubusercontent.com/20589819/186061073-f7567095-4345-4208-ab56-a73668b894e0.png)
在透明度设为0的情况下，渲染的甚至是白色
```js
//symbol
{
  polygonOpacity: 0,
}
```
![vt0](https://user-images.githubusercontent.com/20589819/186061236-65165d9b-f933-4744-ae8a-a7b562b8b9e4.png)

**Comment by fuzhenn** [comment]
duplicate of #60

这个问题今天会修改后发布新版本的
