### ISSUE TITLE
vt支持textName属性字段包含中文

### ISSUE THREAD

**Issue by wsw0108** [maptalks/issues#119]

**Comment by wsw0108** [comment]
https://github.com/maptalks/maptalks.js/pull/1798

**Comment by wsw0108** [comment]
可以考虑把这个通过全局SetXXX类函数暴露出去？

**Comment by fuzhenn** [comment]
支持中文属性名因为会允许很多特殊字符成为变量名，预期会带来其他问题，而中文属性名用简单的正则感觉并不容易识别，暂时不再增加该特性。
