### ISSUE TITLE
bloom在高分屏上运行一段时间会黑屏掉

### ISSUE THREAD

**Issue by deyihu** [maptalks/issues#120]
![QQ图片20220829213855](https://user-images.githubusercontent.com/25998927/187214623-8fb3e60b-65eb-4fe6-b16f-ccb43554b15b.jpg)
![QQ图片20220829213902](https://user-images.githubusercontent.com/25998927/187214634-99b01ddf-9faf-41b8-b15e-c9a804877a6f.jpg)

**Comment by deyihu** [comment]
经大家测试发现和dpr有关

**Comment by fuzhenn** [comment]
fix by https://github.com/maptalks/maptalks.three/pull/528
