### ISSUE TITLE
vt 支持debugdata选项

### ISSUE THREAD

**Issue by deyihu** [maptalks/issues#121]
- vt里加个配置项（类debug），用户开启后，把瓦片数据（不是二进制的，是反序列化后的json）打印出来，然后就好调试了
- 图层写的对不对，属性写的对不对，值写的对不对，一下子就可以确定了

**Comment by fuzhenn** [comment]
VectorTileLayer.options中增加了 debugTileData 选项，用于在控制台中分图层打印瓦片中的数据

![image](https://user-images.githubusercontent.com/13678919/191413318-8e7d2d97-0159-454b-bae8-f2d7490e2e30.png)
