### ISSUE TITLE
核心库 和 gl  两套symbol  默认值有的不一样

### ISSUE THREAD

**Issue by qdhk** [maptalks/issues#123]
**maptalks's version and what browser you use?**
----

**Issue description**

例如  markerVerticalAlignment  一个默认为middle  一个为bottom；

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
markerVerticalAlignment在VectorLayer和PointLayer中，常常用非对称图标绘制兴趣点，所以默认的bottom更合适的值。
但以为矢量瓦片常常用对称icon绘制大量点数据，它的默认值更适合middle一些。

考虑上述不同场景，感觉还是设成不同的默认值可能更符合直觉。（虽然用惯了VectorLayer，在VectorTileLayer中会感觉有点奇怪）
