### ISSUE TITLE
GLTF模型纹理的锯齿感

### ISSUE THREAD

**Issue by fuzhenn** [maptalks/issues#127]
如图中，模型上的纹理贴图会有锯齿感
![image](https://user-images.githubusercontent.com/13678919/188582064-8b8df894-8dfa-45d5-bde8-aefda34b8ae3.png)

测试模型见附件：
[factory.zip](https://github.com/maptalks/issues/files/9494642/factory.zip)

**Comment by fuzhenn** [comment]
但同样的模型 three.js 加载时就不会有锯齿感

**Comment by liubgithub** [comment]
这个模型我在各个平台里面查看都是没有纹理的，不知道是不是数据没有传全，群里上传这个模型的网友也没回复我。
![1](https://user-images.githubusercontent.com/5208386/200204592-4723042b-5cf8-4065-a05c-a822055f0e3d.png)
