### ISSUE TITLE
可视域分析近处的物体没有遮挡住远处

### ISSUE THREAD

**Issue by fuzhenn** [maptalks/issues#142]
如果相机离塔比较近时，塔本身就无法遮挡住后面的物体了。

![image](https://user-images.githubusercontent.com/13678919/192470730-6b9509f7-015f-44ac-95ac-8144879556e9.png)

重现代码：
http://examples.maptalks.com/analysis/viewshed

**Comment by liubgithub** [comment]
fixed by https://github.com/fuzhenn/maptalksgl/pull/321/commits/2257de0242e1041b966ae57450cfd8b7a3fe091f
