### ISSUE TITLE
关于地形的问题

### ISSUE THREAD

**Issue by deyihu** [maptalks/issues#144]
1.不支持自定义tilesize,比如tilesize=256不能正常工作
2.当地形设置了maxAvailableZoom后，skin底图也会被限制，导致地形skin马赛克，正常的效果应该为：
 假设terrain设置了 maxAvailableZoom=14后，当zoom=15后，应该复用terrain=14的数据，但是skin仍然应该加载zoom=15的瓦片来贴图，当zoom=14时，地形的一个瓦片（tilesize=512）上有四个skin瓦片，当zoom=15时，一个地形数据上有16个skin瓦片

**Comment by fuzhenn** [comment]
from @deyihu :

1.当skin加载完成了，检查对应的terrain是否存在，如果存在那么直接往地形上贴，如果不存在那么terrain里默认生成一个plane(一个简单的plane即可,类比tilelayer里的简单plane，比如一个简单的田子形状,只是没有高度而已，贴图足够用了)，这样就可以使skin快速出图，无需等待地形数据的加载完成，否则页面里skin速度明显被地形拉慢了，即使地形数据10s后出来，我也希望立马看到skin

2.当地形数据加载完成，如果其已经生成过默认的plane，这时更行这个plane geomety即可，如果默认的plane没有生成，那么就直接生成对应的地形geometry了

3.当地形数据加载出错，直接为这个地形生成默认的plane即可

4.理论上满屏的所有terrain可以一下子geometry都可以构造好的,无需等待地形数据加载完成的，因为可以为每个地形生成默认的plane的，类似于tilelayer里 plane geometry，等地形数据加载好了，一个一个的更新对应的plane geometry即可

5.一般地形数据最大层级都是14左右，当地图放大后，skin应该还是加载对应的高层级的瓦片，地形数据复用低层级的数据即可，比如 地形设置了 maxAvailableZoom=14，当zoom=16时，skin还是加载zoom=16的瓦片，terrain还是复用 zoom=14的数据
  （1）一种方式是直接复用 zoom=14的geometry
   (2) 另一种方式是还是为zoom=16是生成新的geometry,但是这个geometry,是从zoom=14的身上切割出来的，因为瓦片本来1-4-16这种方式生成的，进行简单的切割应该很容易

示例url:
https://maptalks.org/maptalks.three/demo/terrain.html
