### ISSUE TITLE
GLTFMarker symbol的rotation调整

### ISSUE THREAD

**Issue by fuzhenn** [maptalks/issues#155]
报告人：
群里的 信  

对于GLTFMarker的旋转角度属性，做以下两个调整：
* 取消掉rotation属性，改为rotationX，rotationY， rotationZ
* rotationX，rotationY， rotationZ增加对function-type的支持

**Comment by fuzhenn** [comment]
包括scale和translation：
* scale也改成scaleX， scaleY，scaleZ，并增加function-type支持、
* translation改成translationX，translationY，translationZ，并增加function-type支持

**Comment by liubgithub** [comment]
fixed by https://github.com/fuzhenn/maptalks.gltf/pull/318
