### ISSUE TITLE
关于文档里的SDK 包表格的建议

### ISSUE THREAD

**Issue by deyihu** [maptalks/issues#161]
![_O6W}I{K@8BN23PFFI`9~9H](https://user-images.githubusercontent.com/25998927/198041156-8bb28178-3068-41b8-91d2-b6e9ff401940.png)
建议把这些包给删掉    
理由：

- 用户现在会乱来，既安装 gl-layers，也安装其他的包，导致混乱或者重复安装，出现各种乱七八糟的问题
- 部分用户可能不需要all in one,只用里面的部分包（比如我）,这种用户不需要考虑，他们会自己的去看 `gl-layers`仓库的，他们都知道怎么玩的

**Comment by fuzhenn** [comment]
done
