### ISSUE TITLE
pointGLLayer渲染图片模糊

### ISSUE THREAD

**Issue by just-ads** [maptalks/issues#184]
https://codepen.io/pzd2937/pen/PoaRLyY

**Comment by deyihu** [comment]
可能和这个issue里提到的处理方法有关 https://github.com/maptalks/issues/issues/95

**Comment by fuzhenn** [comment]
有两个原因：
* IconRequestor请求图片时，最大的图标尺寸被设为254导致的，现改为2048
* 计算shape时，基准icon size是24，现改为2048
