### ISSUE TITLE
markerPlacement='line' support   Automatic calculation of tilt angle along the line

### ISSUE THREAD

**Issue by deyihu** [maptalks/issues#195]
![%VRXT6EU 0DU_6CDO87X)L1](https://user-images.githubusercontent.com/25998927/205446115-80b85279-d69c-475e-9b69-afaed5616d28.png)

[image from](https://map.baidu.com/@13427219.824943075,3640992.6079605455,19.78z)

解决方式：

- A configuration item can be added
- ```js
  markerPlacement:'alongline'
```

**Comment by fuzhenn** [comment]
这个功能可以暂时用UTF-8字符串来实现。 例如 →
