### ISSUE TITLE
加载第三方gltf模型时，url无法携带querystring参数

### ISSUE THREAD

**Issue by The-End-Hero** [maptalks/issues#201]
例如加载 https://aliyun.com/test.glb?Access=true 这类地址。
目前这类地址无法加载

**Comment by liubgithub** [comment]
这个地址打开，报404，没有模型吗？

**Comment by liubgithub** [comment]
这个我验证过，是支持的，同时在这个提交中我增加了一个[测试用例](https://github.com/fuzhenn/maptalks.gltf/commit/fefb1a8ce025c3c5eadfaca35881b864056d4cfe#diff-651d67d86c81cbcdfbe2b61ae1d3cabc39cb27235a47aca84da9d87dfd6ae1fa)，所以才疑问是否是链接地址请求不到模型。
