### ISSUE TITLE
vt会主动的readpixels

### ISSUE THREAD

**Issue by deyihu** [maptalks/issues#203]
即使用户么有没有进行ienditfy操作，也会导致内部进行 readpixels,
当主动关闭picking选项后就不会出现这个问题了

这个例子就可以复现  http://examples.maptalks.com/resources/codes/vtLayer/waterStyle/drawText.html?__time=1670576263094

这个例子用户没有调用任何identify操作的

**Comment by deyihu** [comment]
![TKZ5UB1U8 @5ZE~L`KTWP@2](https://user-images.githubusercontent.com/25998927/206667644-3a34bdf0-40be-4f9f-96a7-3815fb9db8a9.png)

**Comment by fuzhenn** [comment]
原因是是GroupGLLayer响应map geometry events时，对是否循环子图层的逻辑有误造成。

改为只有当子图层options.geometryEvents为true时才遍历后解决。
