### ISSUE TITLE
GLTFMarker支持设置height参数

### ISSUE THREAD

**Issue by deyihu** [maptalks/issues#208]
1.当用户不设置时，默认读取模型的数据作为高度
2.当用户设置了height，那么得以用户设置的值作为基准值
3.计算模型的实际高度：height=height*scaleZ

方面和其他的图形一起来统一计算高度，比如building,3dtile等，比如一个建筑物的高度为100m,当一个gltfmarker被用户设置为height=100时，那么其应该和building=100的数据一样高

![OB{$CJ@U9NOFVZ5K5OK @7D](https://user-images.githubusercontent.com/25998927/209511946-5753c389-33a2-46e2-9a31-788855cac5d8.png)

**Comment by fuzhenn** [comment]
duplicate of #329
