### ISSUE TITLE
GLLayer 不支持MultiGeometry

### ISSUE THREAD

**Issue by deyihu** [maptalks/issues#213]

**Comment by fuzhenn** [comment]
原因是GeoJSON.toGeometry转换的Geometry没有symbol，而PolygonLayer中没有提供默认symbol导致的。

初始化数据时，给Geometry提供默认symbol后解决该问题。

**Comment by fuzhenn** [comment]
又深入看了一下，这个其实是maptalks核心库的bug，Polygon是提供了默认样式的，但MultiPolygon没有导致
