### ISSUE TITLE
taoyuan模型默认的高度不正确

### ISSUE THREAD

**Issue by fuzhenn** [maptalks/issues#221]
reporter： deyihu

taoyuan模型不设置heightOffset时，海拔跑到了地下，设置heightOffset后正常。
但以前不设置heightOffset是能正常显示在地上的。

**Comment by deyihu** [comment]
经过排查，这个不是bug，远程仓库里确实加了heightOffset的，是因为本地代码注释了，但是我没有提交代码导致的（上次调试fusiongl里的那个bug时注释掉的） @fuzhenn
