### ISSUE TITLE
加载vt的tube渲染插件 + 大量GLTF模型后卡顿

### ISSUE THREAD

**Issue by fuzhenn** [maptalks/issues#229]
如题载入数据后，拖动一段时间后，页面就会产生卡顿，需要定位是vt的问题还是GLTF图层的问题

**Comment by liubgithub** [comment]
造成卡顿原因是数据量有12285条，直接使用gltfmarker加载不妥，数据中的模型主要是20多类，可以创建20多个multigltfmarker加载，性能会提高不少。其他提高性能的建议有：关闭后处理，减少gltf模型的三角面，减少gltflayer图层数量，减少数据量

**Comment by liubgithub** [comment]
vt渲染插件倒对性能没多大影响
