### ISSUE TITLE
关于gl插件体系里主线程里重复打包 feature-filter function-type

### ISSUE THREAD

**Issue by deyihu** [maptalks/issues#23]
目前核心库里已经把 feature-filter,function-type 这两个包export出来了

https://github.com/maptalks/maptalks.js/blob/3f7c3e4546a995350b65eddae18fdb1147d308d4/src/index.js?_pjax=%23js-repo-pjax-container#L8

vt里主线程里无需重复引用这两个包

![QQ图片20220413134808](https://user-images.githubusercontent.com/25998927/163108911-9e7e2173-830c-4f90-8873-98fbbeb31116.png)

直接引用核心库的就可以了
```js
import {MapboxUtil } from 'maptalks' 
const {createFilter,loadFunctionTypes  ,....}=MapboxUtil ;

```

**至于worker里另当别论**

**Comment by fuzhenn** [comment]
检查了一下，vt中引用feature-filter和function-type的方法都是很基础的方法，同时都在worker和主线程被调用了，要隔离开很麻烦。另外这两个js包个头都很小，建议暂时不用去管他。
