### ISSUE TITLE
gl图层掉两次addGeometry就会白屏

### ISSUE THREAD

**Issue by fuzhenn** [maptalks/issues#232]
变成空白后，移动一下又恢复了

http://localhost/bugs/issue-232/

**Comment by fuzhenn** [comment]
fusion.gl更新到0.5.2后解决，应该是0.5.0版上下文切换时，缺少attributes的启动/禁用逻辑带来的问题，这个问题在0.5.1中得到了解决。

**Comment by deyihu** [comment]
@fuzhenn 把webgl基础设施直接打包到gl

![D7 IW L6LIZI)}5RPMW}R7](https://user-images.githubusercontent.com/25998927/220031187-5872eac1-4664-446d-afc0-e66840e69b8f.png),

这些版本的升级直接用gl来升级，否则会出现用了老版本的gl，仍然会install新版本的 fusion.gl等

如果其他插件要用这些基础的包，在gl里export出来即可
