### ISSUE TITLE
not find map 

### ISSUE THREAD

**Issue by deyihu** [maptalks/issues#235]
![QQ图片20230220162056](https://user-images.githubusercontent.com/25998927/220051036-8a7ba9d4-f4a5-4358-b61c-e7ccb5719deb.png)
![2023-02-20_162111](https://user-images.githubusercontent.com/25998927/220051128-0b6ccec1-79e1-4fea-8bec-5735e1819beb.png)

**Comment by fuzhenn** [comment]
已经解决，是GLTFLayer代码里的问题导致
