### ISSUE TITLE
gltflayer对KHR_materials_common扩展的支持

### ISSUE THREAD

**Issue by liubgithub** [maptalks/issues#236]
https://github.com/KhronosGroup/glTF/blob/ba6ce8891d491f75bb4260f3d0b8592337e6d096/extensions/1.0/Khronos/KHR_materials_common/README.md

**Comment by liubgithub** [comment]
目前glTF标准对KHR_materials_common扩展的支持还处于草案阶段，等正式通过后再做支持

**Comment by fuzhenn** [comment]
KHR_materials_common是一个gltf 1.0标准的草案，是一个大部分引擎不做支持的扩展，这里不做支持
