### ISSUE TITLE
GLTF模型拉近后旋转时，会出现抖动现象

### ISSUE THREAD

**Issue by fuzhenn** [maptalks/issues#24]
见下面的录像：

https://user-images.githubusercontent.com/13678919/163174958-84b3b301-cda6-41cd-bf08-403bb6dd8b81.mp4

模型是用MultiGLTFMarker加载的

**Comment by fuzhenn** [comment]
重现代码，感谢 @deyihu 提供。
[gltflayer-test.zip](https://github.com/maptalks/issues/files/8481225/gltflayer-test.zip)

**Comment by deyihu** [comment]
gltfmarker.copy 性能比较差，见压缩包里的gltflayer-copy-gltfmarker.html例子
[gltflayer-test.zip](https://github.com/maptalks/issues/files/8481300/gltflayer-test.zip)
