### ISSUE TITLE
Geo3DTilesLayer能根据模型的属性值高亮构件吗

### ISSUE THREAD

**Issue by Janexr** [maptalks/issues#247]
Geo3DTilesLayer highlight函数现在是可高亮对应batchId的构件，但是有时两个构件拥有相同的batchId不同的属性值，需要根据属性值高亮构件

**Comment by fuzhenn** [comment]
这个目前不行，也无法做到，因为3dtiles的属性数据里只保存了batchID，即意味着只能用batchID来区分要highlight的三角形面片，你的需求只能通过把这两个构件设置成不同的batchID来实现了
