### ISSUE TITLE
平面裁剪功能画布不再清空

### ISSUE THREAD

**Issue by fuzhenn** [maptalks/issues#257]
因此拖动地图会出现下面这样的重影：
![image](https://user-images.githubusercontent.com/13678919/226239496-450f4383-4dd8-498b-bdf0-7aad9c9b0c97.png)

重现代码：
http://examples.maptalks.com/analysis/cut

**Comment by liubgithub** [comment]
在这个[commit](https://github.com/fuzhenn/maptalksgl/pull/333/commits)中已经处理了这个bug

**Comment by liubgithub** [comment]
fixed by https://github.com/fuzhenn/maptalksgl/pull/333/commits
