### ISSUE TITLE
mtk加载3dtiles树存在问题,在cesium中是正常的

### ISSUE THREAD

**Issue by CharlesLeocc** [maptalks/issues#262]
![}WCQ_8`SH@%4RKRX{)N`P(U](https://user-images.githubusercontent.com/75419761/227092760-0c68fd91-9f06-4eaf-9854-5a99a0251ff3.png)
![)64$75U3G4DP$~N~@5VXXNT](https://user-images.githubusercontent.com/75419761/227092818-fdefbc77-32a4-476c-936a-63bbfc983358.png)

**Comment by fuzhenn** [comment]
参考 #286 ， 引擎中增加了 alphaTest 支持可以解决该问题，不过需要还需要在3dtiles中增加相关逻辑

**Comment by fuzhenn** [comment]
在3dtiles中将alphaTest默认设为了0.99，应该能解决该问题
