### ISSUE TITLE
标记物始终跟着地图转

### ISSUE THREAD

**Issue by wangliangjingok** [maptalks/issues#268]
![Snipaste_2023-03-30_11-04-58](https://user-images.githubusercontent.com/88339076/228717848-b7340afe-cb8f-4f8e-b29e-282d75f75772.png)

**Comment by wangliangjingok** [comment]
期望不会跟着地图转动

**Comment by fuzhenn** [comment]
报告人，qq群的Jing

**Comment by fuzhenn** [comment]
目前没有重现该问题，暂时先关闭，需要的话再打开
