### ISSUE TITLE
PointLayer若设置组合样式，identify可以查到图形但会返回undefined

### ISSUE THREAD

**Issue by cXiaof** [maptalks/issues#27]
### 重现方法
新examples页 http://examples.maptalks.com/ 中，

> 矢量图层-点图层-组合样式

这个例子，在代码最后添加
```js
map.on('click', (e) => {
  map.identify(
    {
      coordinate: e.coordinate,
      layers: groupLayer.getLayers(),
    },
    (geos) => {
      console.log(geos)
    }
  )
})
```

如果没有点选中图形，会打印出

> []

如果点选中了图形，会打印出

> [undefined]

如果点选中了多个图形，会打印出

> [undefined, undefined, undefined]

组合样式无论是设置在Marker上还是设置在Layer上，结果相同

---

另外，
如果不是组合样式，即symbol不是数组，identify可以正常工作。
同样的组合样式，在VectorLayer中，identify也可以正常工作。
LineStringLayer和PolygonLayer没有试，但猜测会有相同的问题。

**Comment by fuzhenn** [comment]
已经解决
