### ISSUE TITLE
模型纹理在GLTFLayer中绘制效果发生了变化

### ISSUE THREAD

**Issue by fuzhenn** [maptalks/issues#280]
报告人： QQ群的 JINKS

![MWJ)DTPSVKSJ_J2DEDMVDDP](https://user-images.githubusercontent.com/13678919/233818706-c8504635-cd89-4293-aabc-b3fbdcec9024.png)

模型：

[chunhu.zip](https://github.com/maptalks/issues/files/11302786/chunhu.zip)

**Comment by liubgithub** [comment]
gltflayer中未重现出来，用户用的是maptalks.three绘制的，会出现这个效果
