### ISSUE TITLE
渲染插件的默认filter需要改进

### ISSUE THREAD

**Issue by fuzhenn** [maptalks/issues#292]
目前渲染插件filter如果不填，则暗示该样式是数据的默认样式，没有被其他渲染插件数据渲染的数据就交由该插件渲染。

但该定义方法在使用中发现含义并不清晰，需要改为更明确的声明方式。

**Comment by deyihu** [comment]
1.任然保持当前的逻辑
2.当用户不写fIlter时，应该给予用户警告提示，这样会导致一定的渲染不确定性，否则用户在style里多个默认值会导致一定歧义，且用户调整这些默认style的顺序，最终渲染的效果完全不同，会对用户造成困扰
3.一般用户是可以用filer写出对数据的分类，如果不能应该增强filter的功能，比如 !in != >-等操作符
4.当用户书写filter=true时，也应该提示用户，这个表示选中所有的数据，会导致数据的重复渲染和性能浪费
5.简而言之就是要尽可能的要求用户书写确定性的唯一性的filter表达式

**Comment by fuzhenn** [comment]
不定义filter时会在控制台中打印警告
