### ISSUE TITLE
tilelayer 和threelayer一起放到groupgllayer里 threelayer里的图形会被tilelayer盖住

### ISSUE THREAD

**Issue by deyihu** [maptalks/issues#293]
https://codepen.io/deyihu/pen/NWOMoGM?editors=1010

不倾斜地图是可以看见的，当地图倾斜后就消失了

**Comment by fuzhenn** [comment]
原因是GroupGLLayer里为了解决图层之间，深度一样时存在的z-fighting问题，给每个图层安排了一个polygonOffset，所以这里tilelayer有polygonOffset，而ThreeLayer没有，导致地图倾斜到一定角度后，three图形的深度被TileLayer盖过后出现这个现象。

解决方案如下：
* ThreeLayer中增加两个方法
  * setPolygonOffset(offset, total), 用于接受GroupGLLayer里分配的polygon offset值 第一个参数是group图层分配的polygonOffset值，total是总值（这里可以忽略）
  * getPolygonOffsetCount，图层所需的polygonOffset计数，ThreeLayer里永远返回1即可
* ThreeLayer中创建Material时，将polygonOffset属性设为上面setPolygonOffset方法中group设置的polygonOffset值
