### ISSUE TITLE
GroupGLLayer的geometryEvents和子图层的geometryEvents的冲突问题

### ISSUE THREAD

**Issue by fuzhenn** [maptalks/issues#3]
以下引述的用户描述：

> grouplayer 设置 geometryEvents: false,
> 下属图层设置 geometryEvents: true, 就不管用了
> grouplayer 设置 true 所有图层设置geometryEvents: false, cpu 还是会涨上去

**Comment by FEJackFly** [comment]
手动点赞

**Comment by fuzhenn** [comment]
通过在GroupGLLayer中增加子图层的geometryEvents逻辑解决
