### ISSUE TITLE
移动端渲染大量数据页面崩溃问题

### ISSUE THREAD

**Issue by cXiaof** [maptalks/issues#30]
移动端渲染大量数据页面崩溃，**可能**主要是因为TextMarker

#### 现象描述
我现在加载了20+M数据约10万个点。
仅初次渲染，没有更新样式。

如果渲染为20w个Marker，正常工作；
如果渲染为10w个Marker+5w个TextMarker，移动端页面偶尔会崩溃；
如果渲染为10w个Marker+10w个TextMarker，移动端页面多数会崩溃。

移动端平台为iPhone13 PM，微信浏览器和Safari浏览器结果相同。

虽然个人**猜测**是瞬间占用了大量内存导致的页面崩溃？但是Safari浏览器偶尔会报`“{页面URL}”重复出现问题。`

PC端目前没有发生此现象。

#### 重现方法
地址：https://cxiaof.github.io/sh-track-info-map/build/
页面是用Github Pages托管的，速度很慢的话，推荐用流量或者翻墙

1. 进入页面会立即开始加载数据，map初始为15级，只会渲染Marker，此时页面不会报错
2. 点击“我知道了”，地图会移动到GPS所在位置并放大到16级（如果不在上海可以不同意获取位置，地图就不会移动，可以手动放大到16级），当zoom>15.5的时候会开始渲染TextMarker，几秒钟后页面崩溃并自动刷新

*页面数据量是逐日增加的，在数据量没有这么大的时候，没有出现这个问题。

**Comment by fuzhenn** [comment]
我估计是文字量太大，用canvas绘制文字的glyph时的问题。
可以试试改成用GeoJSONVectorTileLayer来加载这个数据。
