### ISSUE TITLE
完善地形下地图事件里的坐标信息

### ISSUE THREAD

**Issue by deyihu** [maptalks/issues#304]
![}QOVSH6$@Z1`~ M6{B95CXS](https://github.com/maptalks/issues/assets/25998927/b1604bf7-5464-4906-9c1a-84e8449eef66)

当地图上有地形是，应该完善地图响应事件里坐标的高度信息

- coordinate的高度值，以及在地形下真实的经纬度坐标
- point的值
- 我也不知道point2d是否是地形里面的point值，如果是请完善其值，如果不是请在响应事件里填下新的属性point
- 或者在事件里添加新的字段用于表示地形下的经纬度和point值

**Comment by fuzhenn** [comment]
这个想法是在给DrawTool增加地形支持时产生的，但因为事件层参数影响面比较广，不能简单的在有地形时全都加上地形支持，因为同样的坐标下，有地形时其他容器坐标都会发生变化，会导致一些依赖map事件的逻辑变得复杂或产生bug。
还是应该在实现具体功能时，具体功能具体分析

**Comment by fuzhenn** [comment]
暂时关闭，如果需要进一步讨论再随时打开

**Comment by deyihu** [comment]
可以在事件里加个属性，比如叫terrain(暂时取的名字)

1.方面用户海拔查询
2.方面绘制等工具的使用和适配地形模式
3.这是个全局的功能，可以解决整个系统的凡是用到地形数据的任何地方，可以一劳永逸
4.注意地形数据获取的性能，毕竟mousemove比较频繁
