### ISSUE TITLE
同一图层下identify不穿透，只能找到最上层的图形

### ISSUE THREAD

**Issue by cXiaof** [maptalks/issues#34]
#### 重现方法

新examples页 http://examples.maptalks.com/ 

> 矢量图层-点图层-鼠标点选数据

点击多个图形的重合部分，仅有上层图形被选中。如果是多个图层的重合图形，identify则是找到每个图层的“最上层图形”

作为对比：
旧examples页https://maptalks.org/examples/en/interaction/mouse-identify/#interaction_mouse-identify

> 7交互-7.13鼠标点选图形

点击多个图形的重合部分，所有图形都会被选中

**Comment by fuzhenn** [comment]
这是实现技术造成的问题。
原图层用的是逐个图形比较来判断事件的。
但webgl图层里因为数据量太大，采用了[gpu pick](https://zhuanlan.zhihu.com/p/486282019)的方式来选取图形，所以只能找到最上层的图形，无法穿透
