### ISSUE TITLE
加载的glb模型怎么去跟地图的位置去对应呢 

### ISSUE THREAD

**Issue by huang1005** [maptalks/issues#348]
**maptalks's version and what browser you use?**
----
加载的小区跟跟地图的轮廓对应起来 现在是通过模型的参考点 然后在GIS中选择对应的参考点经纬度但还是有偏差
**Issue description**
----

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
请提供更详细的信息，用什么图层加载的，有怎样的偏差
