### ISSUE TITLE
highlight 隐藏元素bug

### ISSUE THREAD

**Issue by deyihu** [maptalks/issues#355]
http://examples.maptalks.com/examples/cn/vector/style/hide-feature
![VOF0XM 5$M(I2YNMA8N5HQF](https://github.com/maptalks/issues/assets/25998927/31dc4e3a-25ae-4a3a-b675-e2dc805e2a4c)

**Comment by fuzhenn** [comment]
问题是regl中vao的更新存在bug导致，改为vao有更新，即销毁原有vao对象，创建一个新的vao后解决
