### ISSUE TITLE
PointLayer 在地图切换epsg坐标系后，它上面的marker不处于正确区域

### ISSUE THREAD

**Issue by BKx201** [maptalks/issues#388]
PointLayer 在地图切换epsg坐标系后，它上面的marker不处于正确区域，在VectorLayer上则不会出现该问题

**Comment by fuzhenn** [comment]
收到，麻烦提供一个重现代码

**Comment by BKx201** [comment]
https://jsfiddle.net/692sqbd8/33/   
 在121行注释了VectorLayer的图层，麻烦大佬了🙏

**Comment by fuzhenn** [comment]
确认了确实有bug

**Comment by BKx201** [comment]
@fuzhenn 如何解决该问题？

**Comment by fuzhenn** [comment]
这个问题已经解决了，等我们发布新版本就ok了，新版本应该会在一周内发布

**Comment by BKx201** [comment]
好的，谢谢大佬
