### ISSUE TITLE
地形查询数据不正确

### ISSUE THREAD

**Issue by fuzhenn** [maptalks/issues#419]
报告人： deyihu

采用GroupGLLayer.queryTerrain方法查询的高程数值不正确。

重现代码：
http://localhost/bugs/issue-419/terrain1.html

**Comment by deyihu** [comment]
添加新的方法queryTerrainInfo()
返回值要满足：
- 返回当前位置的海拔值
- 返回当前坐标点在地形下的转换坐标，参考3dtilelayer的identify返回值

```js
 altitude:100,
coordinate:[0,0,100]


```
