### ISSUE TITLE
3dtile添加mask（ClipOutsideMask ）不在请求切片数据

### ISSUE THREAD

**Issue by deyihu** [maptalks/issues#431]
https://microget-1300406971.cos.ap-shanghai.myqcloud.com/maptalks-study/layer/3dtile-mask.html

群里： 一又

**Comment by liubgithub** [comment]
例子里面打开，切片数据是请求了的，你的意思是需要支持一下新的特性，mask外的数据不需要请求？

**Comment by deyihu** [comment]
奥，我看了下，大雁塔的这个数据没有子节点，所以放到不会请求数据

**Comment by deyihu** [comment]
- 目前这个功能我本地已经实现，但是需要依赖核心库的bboxutil，需要核心库export bboxutil
- 并优化了getTiles的性能，可以提升一倍，2w+的节点的计算时间有十几ms降到几ms

![(%EGVWAZN}QS $8S_~RP%5B](https://github.com/user-attachments/assets/b7ecce8f-0254-4bbf-b67a-39697d246823)
