### ISSUE TITLE
LineStringLayer 里的 linePatternDx不生效

### ISSUE THREAD

**Issue by deyihu** [maptalks/issues#432]
http://examples.maptalks.com/examples/cn/vector/linelayer/pattern-animation

群里：Outsider

**Comment by fuzhenn** [comment]
确实不支持linePatternDx，LineStringLayer里也不需要实现这个属性，如果是为了实现动画，LineStringLayer上可以用更好的 linePatternAnimSpeed 

http://examples.maptalks.com/examples/cn/vector/linelayer/pattern-animation
