### ISSUE TITLE
底图初始化，显示bug

### ISSUE THREAD

**Issue by tianjzh** [maptalks/issues#45]
初始化的时候，选择多个底图，处于底层的其他底图未设置为隐藏；调用切换底图的方法后正常

`this.map = new maptalks.Map(mapContainer, {
      center: [113, 34.71107610933129],
      minZoom: 1,
      maxZoom: 21,
      zoom: 6,
      overviewControl: {
        maximize: false
      },
      baseLayer: new maptalks.GroupTileLayer('Base TileLayer', [
        new maptalks.TileLayer('Carto light', {
    urlTemplate: 'https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png',
    subdomains: ['a', 'b', 'c', 'd'],
    repeatWorld: false
  })
new maptalks.TileLayer('Carto dark', {
    urlTemplate: 'https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}.png',
    subdomains: ['a', 'b', 'c', 'd'],
    repeatWorld: false
  }),
      ])
    })`

![AB81EFD136769F64EB82C179A9578C7A](https://user-images.githubusercontent.com/11907600/169752640-8287a050-7180-4873-a97a-67f8068bd7d1.gif)

https://user-images.githubusercontent.com/11907600/169752116-2bdda3db-5255-408e-94e2-7499eea1c0bc.mp4

**Comment by deyihu** [comment]
可以提供个完整的例子吗？

**Comment by fuzhenn** [comment]
正常情况下，GroupTileLayer中的图层是全都显示的。
而切换图层控件会人为的其他的图层都隐藏了(layer.hide())，所以才会只显示一个图层。

所以这个问题应该不是bug，如果你想在一开始只显示某个图层，可以先把不需要显示的图层调用hide方法隐藏起来即可。

**Comment by tianjzh** [comment]
ok
