### ISSUE TITLE
vt textName属性在字段为空的时候图形显示不正常

### ISSUE THREAD

**Issue by Xyyue221** [maptalks/issues#462]
我用java+postgis做切片服务，做了一个楼幢的服务，用buildno字段做标注，字段有空值，图形显示异常，而且会抛异常。
因为id是不为空的，我用id作为显示字段的时候图形是正常的。

vt 配置（字段 为buildno 时）有空值图形会变形
![代码](https://github.com/maptalks/issues/assets/36228803/81930198-2395-43f3-a467-e8aec65b7acd)
![非正常](https://github.com/maptalks/issues/assets/36228803/d2d73e14-07fc-4811-9889-609d2539b482)
浏览器异常
![异常](https://github.com/maptalks/issues/assets/36228803/834d61d0-dee6-4b97-b098-a9b5bdf37416)

显示字段换成 id， 显示正常
![正常](https://github.com/maptalks/issues/assets/36228803/368d5bfe-0ab4-43ef-bb4f-403976f1a55e)

**Comment by fuzhenn** [comment]
收到，感谢报告，能不能麻烦整理一个重现代码？

**Comment by Xyyue221** [comment]
ok
&nbsp;


月..
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Fu ***@***.***&gt;; 
发送时间: 2023年10月8日(星期天) 中午1:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [maptalks/issues] vt textName属性在字段为空的时候图形显示不正常 (Issue #462)





 
收到，感谢报告，能不能麻烦整理一个重现代码？
