### ISSUE TITLE
VT快速移动地图视角时，还是不渲染

### ISSUE THREAD

**Issue by deyihu** [maptalks/issues#488]
提交的代码: https://github.com/maptalks/maptalks.js/commit/81667e6b62d3dbb22bb61efa63095a489371b3dc

该问题并没有解决掉

复现例子 http://examples.maptalks.com/examples/cn/3d/line-3d-style/altitude

**Comment by fuzhenn** [comment]
~这个问题是geojson-vt的bug导致，geojson-vt会偶发性的返回空数据（但实际上不是）~
是VectorTileLayer中获得瓦片后，如果瓦片没有数据，没有调用setToRedraw导致，增加setToRedraw后解决
