### ISSUE TITLE
GLTFMarker增加与GLTF内mesh交互的接口

### ISSUE THREAD

**Issue by fuzhenn** [maptalks/issues#491]
报告人： 孟哥

功能包括：
* 能identify出独立的mesh，并读出其中的属性数据
* 能对某个mesh高亮（outline）
* 能改变某个mesh的样式，类似vt的highlight方法

**Comment by zapzqc** [comment]
+1

**Comment by fuzhenn** [comment]
layer的identify结果中增加nodeIndex，返回选中的gltf节点（node）序号。
另外GLTFMarker上增加了下列方法，可以指定highlight或outline的节点序号：
```js
marker.highlightNodes([{ nodeIndex: 0, color }]);
marker.outlineNodes([0, 1, 2]); //数组中为node的序号
```
