### ISSUE TITLE
maptalks.three增加一些demo，效果为polygons瓜分一张大图片

### ISSUE THREAD

**Issue by syks0121** [maptalks/issues#497]
![Snipaste_2023-10-25_16-22-46](https://github.com/maptalks/issues/assets/93832039/877fd689-1dc9-4ef3-b12f-d73efecfc535)
![1L0%F8G~X}U~99 M~M}(BKB](https://github.com/maptalks/issues/assets/93832039/5982b9f1-da93-40a6-a4e2-5bf62090577a)

或许顺便做一下鼠标覆盖时polygon的悬浮动画？麻烦了

**Comment by deyihu** [comment]
close by https://mdpress.glicon.design/p/5enoiCkUaADcSh76yCKjp/YEWU/extrudepolygon_topimage.html

**Comment by fuzhenn** [comment]
新版本的接口已经增加了个该功能支持。

Polygon的symbol中增加了:
```js
polygonPatternFileOrigin: [lon, lat], //图片左上角坐标
polygonPatternFileWidth: 200, //填充图片宽度，单位米
polygonPatternFileHeight: 200, //填充图片高度，单位米，可选属性，不填的话则维持图片原有比例
```

另外ExtrudePolygonLayer中也增加了该属性支持，symbol.material中增加了以下三个属性：
```js
textureOrigin: [lon, lat], //图片左上角坐标
textureWidth: 200,  //填充图片宽度，单位米
// 默认纹理的高度与宽度一致，如果需要设置不同的高度，可以通过调整uvScale来实现
```
