### ISSUE TITLE
地形抛个update事件

### ISSUE THREAD

**Issue by deyihu** [maptalks/issues#510]
- 地形瓦片更新后抛，当且仅当地形瓦片数据渲染完了，或者准备好了，即这时查询地形的值应该为新的值

- tileload估计不行，因为地形可能还没有准备或者渲染好，这时查询地形的值可能不对的

- 总是就是地形的mesh准备好或者渲染好了再抛个事件出来，方面用户被动的去查询地形的海拔值

- 3dtile和vt等也开放类似的事件，方面用户identify

- 事件里要给出当前切片的经纬度的bbox，方便用户利用bbox查询哪些geometry落在这个tile内，方面更新对应的geometry的海拔值

- 事件名叫 `tileupdate`?

**Comment by fuzhenn** [comment]
感觉事件可以叫tileready

**Comment by fuzhenn** [comment]
改为在核心库中把tile加入缓存后再抛tileload事件，这样地形的海拔就能正常查询了
