### ISSUE TITLE
PolygonLayer中Rectangle与Cicrle坐标点z值表现异常，Rectangle rotate函数表现异常

### ISSUE THREAD

**Issue by Janexr** [maptalks/issues#515]
const rect = new maptalks.Rectangle([-0.104049, 51.487568, 100], 1000, 500)本意是设置一个高程为100的矩形，但是渲染结果只有左上角高程100，其他三个点高程0。
同样的，new maptalks.Circle([-0.118049, 51.488568, 100], 500) 圆还是在地面，没有在空中。
![image](https://github.com/maptalks/issues/assets/17001058/f8fa2ac2-ff3a-46c5-8d56-29faddc52266)

rect.rotate(45) 矩形并没有发生旋转，只是发生了位移
![image](https://github.com/maptalks/issues/assets/17001058/6c584edb-b2b6-4ea2-aaf7-aac62acd79c3)

示例：https://codepen.io/Janexr/pen/QWYpMeJ

**Comment by fuzhenn** [comment]
还有Rectangle rotate不正常的问题没解决

**Comment by deyihu** [comment]
@fuzhenn 核心库该问题已经解决，但是发现glrender有问题，应该是 shell处理有点问题，需要读取调用 Geometry._getPrjShell()

核心库已经适配好了glrender的逻辑 https://github.com/maptalks/maptalks.js/pull/2130/files


Rectangle/Ellipse/Sector都已经解决
