### ISSUE TITLE
tileload里查询地形的海拔还是不正确

### ISSUE THREAD

**Issue by deyihu** [maptalks/issues#517]
![CJWBU_%$K@1LF4UR54AQOM8](https://github.com/maptalks/issues/assets/25998927/3cfebe9a-01d8-4398-9528-4e961616b86b)

可能原因：

- 地形查询的方法有问题
- tileload抛的时机还是不是期望的，即地形数据完全准备好了，这时查询的值是最新的

https://github.com/maptalks/issues/assets/25998927/01ddba6c-c52d-4e34-a1f2-40787aa12c29

**Comment by fuzhenn** [comment]
帮忙把这个测试页面发我一下吧

**Comment by fuzhenn** [comment]
tileload本身没有bug，为了减少新数组的创建，返回的height是同一个对象导致的，保存height的时候只保存height[0]就解决了。
不过height单例的设计确实容易出现这种bug，我修改一下吧

![image](https://github.com/maptalks/issues/assets/13678919/c8af9072-0caf-4527-b7c0-da1472bcaad7)


![J@311DN49{{}DYBZCU0C6US](https://github.com/maptalks/issues/assets/13678919/dda1ae28-46db-4501-95da-22e8402d825a)

**Comment by fuzhenn** [comment]
对方法参数做了如下调整：
```js
// out用来接收结果，如果没有提供，则返回新的数组
GroupGLLayer.queryTerrain(coordinate, out)
GroupGLLayer.queryTerrainByProjCoord(prjCoord, out);

```
