### ISSUE TITLE
即使有相同的海拔，LineString和VectorTileLayer在视觉上有偏移

### ISSUE THREAD

**Issue by fuzhenn** [maptalks/issues#539]
报告人： dylanwang97

VectorTileLayer绘制凸起的白模，即使有相同的海拔，相应的LineString和ExtrudePolygon视觉上有偏移

**Comment by fuzhenn** [comment]
目前无法重现

**Comment by leon-wzq** [comment]
报告人：dylanwang97@@可能是数据错误，属于不可预见bug。
