### ISSUE TITLE
PointLayer.addTo(map)直接添加到地图上，里边的marker调用setProperties不到65535次就不会正常触发点击事件了

### ISSUE THREAD

**Issue by wzj8390** [maptalks/issues#541]
http://examples.maptalks.com/examples/cn/vector/pointlayer/marker-events
后面改成
![image](https://github.com/maptalks/issues/assets/128013110/b2411daa-e262-449c-9da4-88d006f67c44)

**Comment by fuzhenn** [comment]
按照您给的重现逻辑，我这里没能重现该问题

**Comment by fuzhenn** [comment]
不过确实发现了两个潜在的问题：
* PointLayer没有构建mesh时，不用管 setProperties 引擎的 propertieschange事件
* 数据的内部id用的数据类型应该从Uint32Array改成Float32Array

我已经修改了上述两个问题，如果您没有回复，到时候可以检查一下下个版本是否修正，如果没有我们再讨论就好

**Comment by fuzhenn** [comment]
后来用户补发了重现代码，确实是id数据类型错误导致的，从Uint32Array改为Float32Array后解决
