### ISSUE TITLE
全球视角下地形会出现白屏

### ISSUE THREAD

**Issue by deyihu** [maptalks/issues#543]
根据我追踪发现满足下面条件才能复现

- 全球视角
- 瓦片大小 512

256瓦片没有这个问题，因为平时都是用256的瓦片所以没有注意到这个问题，但是地形的瓦片512很常见，用512的地形瓦片发现这个问题

因为Terrain基于 tilelayer的原因,我试试下纯的512 tilelayer也是有问题的，故根本原因是tilelayer里逻辑问题

https://github.com/maptalks/maptalks.js/issues/1839

**Comment by fuzhenn** [comment]
该问题属于核心库的bug，这里先关闭
