### ISSUE TITLE
3dtile点云切片 在衔接处断层现象很明显而cesium 正常

### ISSUE THREAD

**Issue by qdhk** [maptalks/issues#547]
**maptalks's version and what browser you use?**
----
最新的

**Issue description**
----

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment]
![XFA)ZRWL@3)QP7FOFPW78ZE](https://github.com/maptalks/issues/assets/13678919/27583d92-13fc-49de-9dec-97c1ab116689)
