### ISSUE TITLE
MeshPhysicalMaterial材质与GroupGLLayer结合使用出现报错

### ISSUE THREAD

**Issue by tttttttanghc** [maptalks/issues#55]
复现地址：https://codepen.io/tttttttanghc/pen/XWZqxYw?editors=0010，把addExtrudePolygon函数中的MeshPhongMaterial换成MeshPhysicalMaterial即可

**Comment by deyihu** [comment]
https://github.com/maptalks/issues/issues/237

**Comment by fuzhenn** [comment]
fixed in @maptalks/gl-layers@0.26.0
