### ISSUE TITLE
矢量瓦片图层identify接口返回的数据结构有问题

### ISSUE THREAD

**Issue by luxiousCoder** [maptalks/issues#556]
![image](https://github.com/maptalks/issues/assets/59036635/74ec60f3-d935-45ee-b3c4-5df53503d6a6)
返回type为Point，但是coordinates数据嵌套了

**Comment by liuxuechao01** [comment]
[Uploading test1.zip…]()

**Comment by luxiousCoder** [comment]
[test1.zip](https://github.com/maptalks/issues/files/13769532/test1.zip)

**Comment by luxiousCoder** [comment]
其他类型数据没有测，修复的时候一并测一下
