### ISSUE TITLE
大体量矢量瓦片数据渲染内存暴涨

### ISSUE THREAD

**Issue by luxiousCoder** [maptalks/issues#559]
在使用vectorTileLayer时，前端需要调用identify和根据几何图形（矩形、多边形等）查询数据，因为单图层数据量已达到千万级，开启features: true,pickingGeometry: true,后，发现前端内存暴涨，页面经常会卡死，在renderer上，挂了一个tileCache，把瓦片数据存进去了，地图缩放一会儿，内存就爆了

**Comment by fuzhenn** [comment]
可以考虑把features数据存入indexdb，不在内存中缓存整个features，并省去features从worker传输到主线程的性能损失。

**Comment by fuzhenn** [comment]
VectorTileLayer.options中增加了`features: 'transient' `支持，设置后，用户可以在tileload事件中获取到所有features，图层会在tileload事件后，把worker中获取的features删掉（但会保留function-type所需的属性）以节省内存

```js
      const vt = new maptalks.VectorTileLayer("vt", {
        features: 'transient',
        urlTemplate: `https://api.mapbox.com/v4/mapbox.mapbox-streets-v8/{z}/{x}/{y}.vector.pbf?access_token=${token}`
      });

      vt.on('tileload', e => {
        const features = e.tileImage.features;
      });
```
