### ISSUE TITLE
threelayer toPoints和linelayer的空间关系在地图缩放时会发生变化

### ISSUE THREAD

**Issue by Janexr** [maptalks/issues#564]
示例可见：https://codepen.io/Janexr/pen/gOEpLbq

![JC~GW`$LFBK}HWQRBIUJX{1](https://github.com/maptalks/issues/assets/17001058/f17a86bf-1b41-49ee-bbf5-6035fdda220d)
![L1_V7T001{5_~1D@M7 7Q5R](https://github.com/maptalks/issues/assets/17001058/1d66af8e-d713-4b6a-b36b-9eed8aeae94c)

**Comment by fuzhenn** [comment]
不是bug，是点和线高度一样导致的z-fighting
