### ISSUE TITLE
maptalks加载超图发布的3dtiles是url里面的特殊字符没有做encodeURIComponent 处理

### ISSUE THREAD

**Issue by wang88633** [maptalks/issues#57]
![WS1 )ZD5 %~3M7FRP J OZ3](https://user-images.githubusercontent.com/22592035/172519389-4830ef86-90c9-4f7b-ab5c-353f59f6354d.jpg)

![2(CGQ6 PMY1HCUTI_4B%0$F](https://user-images.githubusercontent.com/22592035/172519398-7e0785b8-3498-4e3d-8672-5391901739ff.jpg)

**Comment by fuzhenn** [comment]
已经针对supermap iServer做了特殊处理
