### ISSUE TITLE
PolygonLayer VectorLayer相同颜色显示不一致

### ISSUE THREAD

**Issue by tpolong** [maptalks/issues#60]
maptalks v1.0.0-rc.6
maptalksgl.js:25998 @maptalks/gl v0.70.3
maptalks.vt.js:21316 @maptalks/vt v0.67.1
chrome :102.0.5005.63
问题样例：https://codepen.io/tpolong/pen/zYraVrq

**Comment by tpolong** [comment]
您好，您的邮件已收到，谢谢！

**Comment by fuzhenn** [comment]
调整shader中透明度的逻辑后，目前仍然存在一些颜色不一致

**Comment by fuzhenn** [comment]
gl-layers v0.12.6中应该已经解决了该问题
