### ISSUE TITLE
GroupGLLayer的锯齿有点严重

### ISSUE THREAD

**Issue by deyihu** [maptalks/issues#61]
只要开启后处理，锯齿非常严重，即使开启原生的msaa,我测试i3s服务也是一样的

```js
const sceneConfig = {
  postProcess: {
    enable: true,
    // antialias: { enable: true }
  }
};
const groupLayer = new maptalks.GroupGLLayer('_group', [], { sceneConfig, antialias: true });
```
所以猜测是是后处理逻辑里有点问题

https://codepen.io/deyihu/pen/KKoVxOy?editors=0010

**Comment by fuzhenn** [comment]
需要用webgl 2的新方法，renderbufferStorageMultisample 来开启framebuffer的msaa特性：
http://www.realtimerendering.com/blog/webgl-2-new-features/
https://developer.mozilla.org/en-US/docs/Web/API/WebGL2RenderingContext/renderbufferStorageMultisample
