### ISSUE TITLE
如何在maptalks地图上实现扫光脉冲圈的效果，maptalks是否支持自定义后处理特效呢？

### ISSUE THREAD

**Issue by dodotorry** [maptalks/issues#615]
您好，我们项目上有个特效需求，需要有个扫光圈特效作用在地图上，我看到three.js中该特效是通过shaderPass来实现的，请问maptalks支持这种自定义后处理特效吗
![20240228-111022](https://github.com/maptalks/issues/assets/24838226/1a29b63b-e215-485c-b61f-3cdb5afbaa6c)

**Comment by fuzhenn** [comment]
目前还不支持，不过我们在考虑把各个图层的shader通过某种方式能允许自定义，这样就可以通过类似shaderPass的方式来实现这样的特效了。

**Comment by fuzhenn** [comment]
另外maptalks的GroupGLLayer里有后处理逻辑，感觉可以参考three，增加对ShaderPass类似定义方式的支持，你这里是否有这个光圈效果ShaderPass的示例？我可以尝试实现一下

**Comment by dodotorry** [comment]
您好，我这边找到的后来发现都是shader材质结合去实现的：https://gitee.com/honbingitee/particle，后处理通道没有尝试出很完美的解决方案
我的wx号是：dodotorry，方便加我微信一起探讨一下吗

**Comment by liubgithub** [comment]
已增加支持 fixed by https://github.com/fuzhenn/maptalksgl/pull/20
