### ISSUE TITLE
多个图层使用地图碰撞时，修改marker会导致当前图层地图碰撞失效

### ISSUE THREAD

**Issue by wzj8390** [maptalks/issues#629]
![CL(XR(O0VFI R2W2@Q}Y_@R](https://github.com/maptalks/issues/assets/128013110/4264817c-bc6c-42e2-a51e-8c99e8433222)
![}``N}PP I$P(FSW%MFC@PG2](https://github.com/maptalks/issues/assets/128013110/3b25f607-ac0b-4096-a124-4710972ffda2)
![image](https://github.com/maptalks/issues/assets/128013110/ac765775-113a-4960-9bda-76b563af39ed)

**Comment by deyihu** [comment]
假设当前地图上有两个layer:

- 地图渲染帧里永远在clear碰撞器，即会清空两个图层的碰撞盒子
- 当一个图层触发了redraw，这时这图层碰撞时，注意这时地图的碰撞器里是空的，另一个图层的碰撞盒子并没有参与碰撞
- 正确的方法应该是，任何一个图层触发redraw时，所有的图层的碰撞应该重新碰撞
