### ISSUE TITLE
从json创建的map不能正常的拖动地图

### ISSUE THREAD

**Issue by fuzhenn** [maptalks/issues#641]
报告人： rockmap

![~M(~_~1`HF$Y{8JJPH~N~P5_tmb](https://github.com/maptalks/issues/assets/13678919/4a18e211-29b4-436c-8ef0-48bc4ff7cab8)

 把这个去掉就 完全不能操作地图了

重现代码：
http://152.136.165.70/maptalks/5.html

**Comment by deyihu** [comment]
这不是个bug，是用户自己手动禁用地图相关操作导致的
![H0LARAT_Z8UEW`E8L@C Z2T](https://github.com/maptalks/issues/assets/25998927/46a2afa7-25f1-4009-b78c-0a2057f7e4ec)
