### ISSUE TITLE
GLTFMarker调用zoomTo报错

### ISSUE THREAD

**Issue by fuzhenn** [maptalks/issues#650]
报告人：yy

GLTFMarker调用zoomTo报错

**Comment by liubgithub** [comment]
这个是因为核心库里面的setCameraPosition方法换成了setCameraOrientation方法导致的

**Comment by fuzhenn** [comment]
> 这个是因为核心库里面的setCameraPosition方法换成了setCameraOrientation方法导致的

收到，已修改

**Comment by liubgithub** [comment]
fixed by https://github.com/fuzhenn/maptalksgl/pull/38
