### ISSUE TITLE
怎样动态更新vt里一个feature的样式？

### ISSUE THREAD

**Issue by deyihu** [maptalks/issues#66]
比如用户点击了一个feature，然后动态的设置这个feature的样式

1.目前我看feature的样式以枚举的方式写到featureStyle里的，动态那么意味无法枚举了

```js
 featureStyle: [
      {
        id: 12,
        style: [
          {
            renderPlugin: {
              dataConfig: {
                type: 'fill'
              },
              sceneConfig: {},
              type: 'fill'
            },
            symbol: {
              visible: false,
              polygonFill: '#577570'
            }
          },
          {
            renderPlugin: {
              dataConfig: {
                type: 'line'
              },
              sceneConfig: {},
              type: 'line'
            },
            symbol: {
              visible: true,
              lineColor: [1, 0, 0, 1],
              lineWidth: 2
            }
          },
        ]
      }
    ]

```
2.另外我看了例子里关于featureStyle有个id字段标识，其表示？

- 数据里有个有条数据他的id字段为12
- 表示数据的下标索引？如果是，那么我觉得用id表示不合理，应该用index:12

**Comment by fuzhenn** [comment]
这个id是geojson规范中feature的id值，不是index

**Comment by fuzhenn** [comment]
VectorTileLayer中增加了以下用于更新style和featureStyle的方法：
* addRenderStyle(style)
* updateRenderStyle(index, style)
* updateRenderStyleByName(name, style)
* removeRenderStyle(index)
* removeRenderStyleByName(name)
-----
* addFeatureStyle(featureStyle)
* updateFeatureStyleById(ifeatureStyle)
* removeFeatureStyleById(id)
* getFeatureStyleIndex(index)
------
无刷新更新样式的方法：
* updateSymbol(idx, symbol)
* updateFeatureSymbol(id, featureStyleIndex, symbol)

----
忘记添加的待添加新方法：
updateSymbolByName(name, symbol)


以上方法应该足够用于维护style了

**Comment by fuzhenn** [comment]
updateSymbolByName(name, symbol) 也已经添加
