### ISSUE TITLE
RoutePlayer 播放完重新播放 在playend事件里 为啥不成功呢 ？还得加个settimeout 大佬遇到过吗？

### ISSUE THREAD

**Issue by lzp0070007** [maptalks/issues#669]
![ZEE(__ZLKPIO@4QCNS({YUQ](https://github.com/maptalks/issues/assets/5045130/8b9c4dd6-fe01-4c6f-8f76-581c85fc0250)

**Comment by deyihu** [comment]
fix by https://github.com/maptalks/maptalks.routeplayer/commit/cece4a5ca873c12d5b7e86f22a3d06c522ffaa97

@fuzhenn  need new version for maptalks.routeplayer plugin

**Comment by fuzhenn** [comment]
已经发布，1.0.0-rc.1
