### ISSUE TITLE
vue将map加入状态管理后导致内存暴涨

### ISSUE THREAD

**Issue by fuzhenn** [maptalks/issues#684]
报告人： 冰樱湛蓝

> 我原本的代码就是用maplibre的，结果换成mtk 内存直接爆了，所以我才有疑问的

**Comment by deyihu** [comment]
通过和用户讨论和证明，这个问题就是vue的问题

- mtk的地图相对于maplibre要复杂
- 内存爆不爆取决于对象的复杂度
- 非地图对象，只要其足够复杂照样爆内存
- maplibre 不爆内存不代表就是对的
- 任何复杂的对象都不应该被双向绑定
