### ISSUE TITLE
关于VideoMask的几点想法

### ISSUE THREAD

**Issue by szoyaung** [maptalks/issues#685]
### 在issues里看到 #259 ，可以使用VideoMask实现类似视频融合功能，测试了一下，由于找不到文档，所以就直接从打包好的gl.min.js中查看了一下，发现VideoMask继承于Polygon类，有以下几点建议：

1. 是否可以针对maptalks-gl-layers出一个完整的文档（因为gl没有开源，有一些功能gl的例子里应该是没有体现的，所以无法找出如何使用）
2. 从 #289 里可以看到可以使用ElementId的方式关联Video标签中的视频，这里还是需要有个文档说明
3. 如果目前只提供了VideoMask实现“视频融合”的功能，是否可以设置多个VideoMask，因为一般业务场景中可能需要多个视频同时展示
4. VideoMask播放的视频（设置在Geo3DTilesLayer图层上），只有被整个建筑物包裹的VideoMask面的视频画面才是正常的，如果VideoMask的面很大，中间没有3dTile物体的部分，是没有视频画面的。当然这个问题可能是我的使用方式不对引起的。

### 下面是第4点的一个视频画面

https://github.com/maptalks/issues/assets/16623273/937c3813-195f-4dcf-85e7-6bce5b7b2a28

### 以上只是个人的几点建议或遇到的问题。也感谢作者的开源贡献，对于未接触过gis的前台开发人员来说，maptalks要比mapbox入门简单、快捷很多。

**Comment by fuzhenn** [comment]
除了VideoMask，还有个VideoLayer + VideoSurface能实现视频融合，可以根据需要选用：

http://examples.maptalks.com/examples/cn/3d/video/add

目前代码正在筹备开源中，只是因为人手不足，文档和示例的整理都需要很多工作量，需要一些时间才能正式就绪了。

**Comment by szoyaung** [comment]
> 除了VideoMask，还有个VideoLayer + VideoSurface能实现视频融合，可以根据需要选用：
> 
> http://examples.maptalks.com/examples/cn/3d/video/add
> 
> 目前代码正在筹备开源中，只是因为人手不足，文档和示例的整理都需要很多工作量，需要一些时间才能正式就绪了。

感谢百忙之中回复！

嗯嗯，VideoLayer+VideoSurface之前也试了一下，好像这个无法实现视频的贴建筑物表面（还是有可能我参数没设置到位~），比如地图中加载一个3dtiles图层，视频看着是悬空的，挡住了下面的建筑物。

![image](https://github.com/maptalks/issues/assets/16623273/a5ff21ce-1bbe-49c8-9288-eea424abc006)

我先把这个issue关了，等gl有文档了或者开源了我再尝试一下。👍👍👍
