### ISSUE TITLE
目前地图相机的远视面不够远

### ISSUE THREAD

**Issue by fuzhenn** [maptalks/issues#705]
远视面不够远，会在渲染某些较大模型时，出现如图下的现象：

![image](https://github.com/maptalks/issues/assets/13678919/9724a24d-e80a-4d3c-8e08-cb2440af7d37)

需要合理的将远视面拉远一些

**Comment by deyihu** [comment]
This parameter may solve this problem
![PHL $Y%AJW98)3SJCP`3 KC](https://github.com/maptalks/issues/assets/25998927/6e751850-3c20-410b-950f-3f5b344385b4)

**Comment by fuzhenn** [comment]
> This parameter may solve this problem ![PHL $Y%AJW98)3SJCP`3 KC](https://private-user-images.githubusercontent.com/25998927/346393986-6e751850-3c20-410b-950f-3f5b344385b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MDgxMzksIm5iZiI6MTcyMDQwNzgzOSwicGF0aCI6Ii8yNTk5ODkyNy8zNDYzOTM5ODYtNmU3NTE4NTAtM2MyMC00MTBiLTk1MGYtM2Y1YjM0NDM4NWI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDAzMDM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkZjc3NGZjMGRiNzllNTYzNTNlY2MxOTMwYzBkYWFlMDM5NDIxNDM3MzViZGRkMTdjNzU3ZDM0MTE3ODg1YmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x5FPyrPmUm9kSC5qMPhx-o0em9r-3-2oEDFhkgzmXnE)

这个参数有点太暴力了，会造成视锥内数据量太大，对性能影响还是蛮大的。
应该优先找个更合理的cameraFar的计算逻辑

**Comment by fuzhenn** [comment]
### 测试参数：
* map容器高度：1271
* map容器宽度： 1491
* 地图参数
```js
{ "center":[-74.0808754,40.63616773],"zoom":15,"pitch":80,"bearing":-72 }
```
### cameraFar与瓦片数量关系：

看上去瓦片数量和cameraFar的值并不完全相关。

* `4 * cameraToCenterDistance`: 81
* `10 * cameraToCenterDistance`: 78
* `14 * cameraToCenterDistance`: 101
* `20 * cameraToCenterDistance`: 92

**Comment by fuzhenn** [comment]
感觉比较合适的思路如下：
* zoom大的时候增大cameraFar的比例，因为此时视距再远，加载的数据量也不会很大
* zoom比较小的时候，可以适当缩小cameraFar的比例

需要按照上面的思路，寻找一个与zoom有关的cameraFar计算公式

**Comment by fuzhenn** [comment]
用 ```cameraFarUndergroundInMeter``` 来保障相机对地下的最低视距（默认2000米），计算出来的cameraFar和原本的相机距离相比取最大值。

这样在zoom较大时，也能维持一个合理的cameraFar（至少保证看到地下2000米）
