### ISSUE TITLE
vt pick 导致 reshader里报undefined

### ISSUE THREAD

**Issue by deyihu** [maptalks/issues#74]
![QQ图片20220705091653](https://user-images.githubusercontent.com/25998927/177231258-b30db8fc-b851-4cc0-bd2f-974a90b2efeb.png)
![QQ图片20220705091659](https://user-images.githubusercontent.com/25998927/177231262-01c8256a-cebe-4a7a-8fad-2516c6a825e9.png)

**这个问题还挺严重，直接导致整个页面停止运行了，**
并不是用户手动去identify导致的，即用户没有去vt.identify操作，应该是vt内部有个默认的idenfity操作

**Comment by fuzhenn** [comment]
这个问题已经解决，gl版本更新后就能正常了
