### ISSUE TITLE
請問 Geometry 的 translate 未來是否可以支援 z軸移動，或不清空 z軸?

### ISSUE THREAD

**Issue by andy26283** [maptalks/issues#741]
![image](https://github.com/user-attachments/assets/0ad502a2-f94b-4a07-8ccc-b220a2add65c)
如上圖所示，只要使用 translate 後，其點位的 z 會被清空。
這會導致移動後，就失去 3D的資料

**Comment by fuzhenn** [comment]
这应该是个bug，会在下个版本中解决
