### ISSUE TITLE
default roughnessFactor and metallicFactor

### ISSUE THREAD

**Issue by liubgithub** [maptalks/issues#749]
测试用例里面有个模型渲染出来是纯黑色
[2.zip](https://github.com/user-attachments/files/17186301/2.zip)

**Comment by fuzhenn** [comment]
确实会有这个现象，按照three.js的光照逻辑进行修改后，除非有ibl，否则纯的环境光再亮，纯金属都是黑色的。

可以把模型放到three.js的[gltf-viewer](https://gltf-viewer.donmccurdy.com/)来验证，右边的lighting里，environment选择为none

**Comment by liubgithub** [comment]
经过验证，three也是这样
