### ISSUE TITLE
下雨没有雨滴

### ISSUE THREAD

**Issue by fuzhenn** [maptalks/issues#754]
![64f0c8d900337ea93dde191c88c9e03a](https://github.com/user-attachments/assets/2485443e-5221-4aff-9210-11cd8c5faf4d)

[rain没有雨滴.zip](https://github.com/user-attachments/files/17289467/rain.zip)

**Comment by liubgithub** [comment]
没有重现问题，可能是图片资源路径不对

**Comment by Criska9527** [comment]
![image](https://github.com/user-attachments/assets/55bf5e2a-e8ff-4ef3-b1aa-aa4eb0136cf8)
资源可以访问到，依然没有雨滴

**Comment by minemine-m** [comment]
![image](https://github.com/user-attachments/assets/479fc012-0991-4c6e-bea1-930e2c97a4d9)
资源访问到了，依然没有雨滴

**Comment by fuzhenn** [comment]
后反映是资源跨域导致
