### ISSUE TITLE
设置gltfmarker的透明后 不起作用 必须隐藏再显示这个gltf才能成功设置透明度

### ISSUE THREAD

**Issue by lzp0070007** [maptalks/issues#760]
设置gltfmarker的透明后 不起作用 必须隐藏再显示这个gltf才能成功设置透明度
let uniforms={
          polygonOpacity: _this.opacity,
        }
gltfMarker.setUniforms(uniforms);
![8%@ 52 {)5{UUSYH$LM7QWE](https://github.com/user-attachments/assets/e3d4e6df-96c9-494d-8fa4-edf9c091bd8a)

感觉现在设置一些options后 都是这个问题 不起作用  必须要调用下其他的方法才行

**Comment by liubgithub** [comment]
[issue-760.zip](https://github.com/user-attachments/files/17376223/issue-760.zip)
没能重现这个问题，看是不是版本的问题，这个是我尝试重现的例子 @lzp0070007

**Comment by lzp0070007** [comment]
> [issue-760.zip](https://github.com/user-attachments/files/17376223/issue-760.zip) 没能重现这个问题，看是不是版本的问题，这个是我尝试重现的例子 @lzp0070007

[新建文件夹.zip](https://github.com/user-attachments/files/17376953/default.zip)
我是用 npm的方式安装的包 请帮忙看看

**Comment by fuzhenn** [comment]
[mtk-project.zip](https://github.com/user-attachments/files/17553129/mtk-project.zip)

rockmap 提供的重现代码

**Comment by liubgithub** [comment]
需要@fuzhenn 来看一下，这个问题某些模型polygonOpacity起作用，某些模型不起作用，通过spector查片元着色器, polygonOpacity值传递正常，不知道是不是和材质判断有关，而且这个问题应该是从某个版本修改后导致。

**Comment by fuzhenn** [comment]
可能是alpha cutOff的设置，而原逻辑是polygonOpacity在alphaCutoff计算前计入的，所以alpha被alphaCutoff覆盖掉了。

但因为用户没有提供出错的模型，目前我这里暂时无法验证，在这里先记录。
