### ISSUE TITLE
MultiGLTFMarker 无法添加 id\type 属性，只能放在 properties 中，造成读取方式不一致；也无法直接获得 data 数据。

### ISSUE THREAD

**Issue by zhanghp007** [maptalks/issues#762]

**Comment by liubgithub** [comment]
我这边测试是可以添加id的，也可以获取data, 至于你要添加的type, 可以放在properties里
![image](https://github.com/user-attachments/assets/94631e58-9052-4ca1-a703-fdc54f3f920b)

**Comment by zhanghp007** [comment]
谢谢，的确赋 id 后，可以通过 getGeometryById 获取到对象！ 我是将对象 JSONStringify 后，发现没有 id，所以以为  id 无法设置，也无法通过 id 获取对象。
