### ISSUE TITLE
GLTFLayer频繁clear和添加GLTFMarker后报错

### ISSUE THREAD

**Issue by fuzhenn** [maptalks/issues#77]
错误内容见下面的截图：

![7B{(IKY`@I1 63XN)SBT0X3](https://user-images.githubusercontent.com/13678919/177263889-b544c3db-8da2-49e2-a49a-2e95e83799ad.jpg)

**Comment by liubgithub** [comment]
fixed by https://github.com/fuzhenn/maptalks.gltf/pull/307
