### ISSUE TITLE
当drawTool drawstart的时候设置 样式会报错

### ISSUE THREAD

**Issue by lzp0070007** [maptalks/issues#779]
![4f6d70adf2c1cdacc0f950295f17c989](https://github.com/user-attachments/assets/53dcea1d-1cf7-4f0c-9b48-82f835aeb084)
![0951e2ffab9621a0fec03c88065da3c5](https://github.com/user-attachments/assets/3ce79dc0-b527-48b8-8cdf-8fc648b15700)
[draw.zip](https://github.com/user-attachments/files/17539908/draw.zip)

**Comment by deyihu** [comment]
fix by https://github.com/maptalks/maptalks.js/commit/adba02652f2dbce6631032125478e3dfcf65e46f
