### ISSUE TITLE
MultiGLTFMarker批量生成的Marker，能否单独设置某一个marker的highlightNodes

### ISSUE THREAD

**Issue by dingxuejin** [maptalks/issues#784]
为了性能我选用了MultiGLTFMarker来生成近1000个小汽车实时在路上行驶，数据一秒钟会更新6次，请问可以根据数据来改变这些小汽车的车漆颜色吗，不能改变轮胎和玻璃的颜色

**Comment by fuzhenn** [comment]
@liubgithub  不过如果GLTFMarker内部没有用InstancedMesh实现的问题解决的话，用户也可以改用GLTFMarker来实现该功能，就可以直接调用GLTFMarker上的highlightNodes接口，不用实现该功能了。

**Comment by liubgithub** [comment]
instancedMesh还不支持highlightNodes，还得实现一下，目前highlightNodes是写入的unfiorms，会全局影响，instancedMesh要支持的话，需要写入到instanceData里面，也就是attributes里

**Comment by fuzhenn** [comment]
后来确认已经实现过了，只是没写示例
```js
// 第一个参数是marker的编号
multiGLTFMarker.highlightNodes(1,
[{
  nodeIndex: 0,
  color: [0.8, 0, 0, 1],
  bloom: true
}]
);
```
