### ISSUE TITLE
使用ColorMask绘制在3dtiles上部分面不能点击的问题

### ISSUE THREAD

**Issue by linxiangWang** [maptalks/issues#790]
[ColorMask-click.zip](https://github.com/user-attachments/files/17800398/ColorMask-click.zip)
![image](https://github.com/user-attachments/assets/56997f45-99a1-42d3-b0f4-8f6d7a1e6adf)

**Comment by liubgithub** [comment]
https://github.com/user-attachments/assets/fd0c4090-c687-4967-85d1-3fd1c52bde3c
已修复
