### ISSUE TITLE
GLTFLineString  用map.toJSON() 导出为json后 data里面不是原来的3个点位置信息  生成了 很多个点 （36个）

### ISSUE THREAD

**Issue by lzp0070007** [maptalks/issues#799]
GLTFLineString  用map.toJSON() 导出为json后 data里面不是原来的3个点位置信息  生成了 很多个点 （36个）  然后把这个json用new maptalks.Map.fromJSON(this.id, mapJson); 初始化 也会报错
![604fe4bc45c19de8a2ac728e97d6640f](https://github.com/user-attachments/assets/9b66400f-6f62-496e-a4cb-480f72c563d3)
![75962934113163cba9ae8dfaa2c214ad](https://github.com/user-attachments/assets/30ea6e52-d774-415e-b5ce-0e30b5b28484)

**Comment by liubgithub** [comment]
@lzp0070007 GLTFLineString会根据线条在中间插值模型，所以生成36个模型是正常，比如沿着路线种树。如果不希望插值，可以直接用GLTFMarker或者MultiGLTFMarker。另外Map.fromJSON报错是个bug，这个会在下个版本改过来
