### ISSUE TITLE
gltfMarker的url 不能带参数 比如 https://xxx.glb?token=123

### ISSUE THREAD

**Issue by The-End-Hero** [maptalks/issues#83]

**Comment by liubgithub** [comment]
方便提供一个可以测试的url么

**Comment by The-End-Hero** [comment]
@liubgithub 
doc示例中添加query string，就会出现相同错误，请求并没有发出
![image](https://user-images.githubusercontent.com/19590233/183645610-08233b5c-8702-402e-bfce-8d3571ffada4.png)
