### ISSUE TITLE
PointLayer和ThreeLayer用同一种图片画出来的对象显示效果有较大差别

### ISSUE THREAD

**Issue by tttttttanghc** [maptalks/issues#88]
![image](https://user-images.githubusercontent.com/75002405/179708616-0ed918b4-ce60-4df7-bc5d-a97b0815fb51.png)
示例：https://codepen.io/tttttttanghc/pen/XWZqxYw

**Comment by fuzhenn** [comment]
生成纹理时保持图片原有尺寸而不再缩小图片，解决了该问题
