### ISSUE TITLE
地图缩小后，线会出现断裂的现象

### ISSUE THREAD

**Issue by fuzhenn** [maptalks/issues#9]
![TA%EZ}AY8OX__~ALADR R(8](https://user-images.githubusercontent.com/13678919/157393450-f4a01269-7338-4c82-87fc-494e746a666c.jpg)

重现代码：
http://localhost/bugs/memo-69/

**Comment by fuzhenn** [comment]
是geojson-vt里的简化算法把线段删除掉导致的，在geojson-vt中需要增加retain points的配置

**Comment by wsw0108** [comment]
这个应该是要改geojson-vt的option的tolerance值？

**Comment by fuzhenn** [comment]
转为[@maptalks/geojson-vt](https://github.com/fuzhenn/geojson-vt)后解决.
