### ISSUE TITLE
setInfoWindow设置的对话框，有时候在地图旋转后，与所点击对象的对齐会产生偏差

### ISSUE THREAD

**Issue by tttttttanghc** [maptalks/issues#91]
setInfoWindow设置的对话框，有时候在地图旋转后，与所点击对象的对齐会产生偏差
https://codepen.io/tttttttanghc/pen/bGvrZrz?editors=1010
![WZBRAEHK@8)A 0 MCT0H _T](https://user-images.githubusercontent.com/75002405/181144401-9a5b98cb-e790-4dab-bdf0-f03d241d514e.png)

**Comment by deyihu** [comment]
fix by https://github.com/maptalks/maptalks.three/commit/b5fca51e266c9a6566f84726f90fe950ce8ddde8
